name: "Bot: Send Close Pull Request Signal"

on:
  pull_request:
    types:
      [closed]

jobs:
  send-close-signal:
    name: "Send closing signal"
    runs-on: ubuntu-22.04
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: "Create PRtifact"
        run: |
          mkdir -p ./pr
          printf ${{ github.event.number }} > ./pr/NUM
      - name: Upload Diff
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr
